import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'node:test'

const articleDetailPath = resolve(process.cwd(), 'src/pages/subPage/NewsArticleDetail.tsx')
const markdownArticlePath = resolve(process.cwd(), 'src/features/news/MarkdownArticle.tsx')
const markdownRendererPath = resolve(process.cwd(), 'src/features/news/markdownRenderer.tsx')
const newsAnchorPath = resolve(process.cwd(), 'src/features/news/newsAnchor.ts')
const articleTocPath = resolve(process.cwd(), 'src/features/news/ArticleToc.tsx')
const newsDocumentsPath = resolve(process.cwd(), 'src/features/news/newsDocuments.ts')
const indexCssPath = resolve(process.cwd(), 'src/index.css')
const routerPath = resolve(process.cwd(), 'src/routers/index.tsx')
const messageBoardPath = resolve(process.cwd(), 'src/pages/subPage/MessageBoard.tsx')
const messageBoardDetailPath = resolve(process.cwd(), 'src/pages/subPage/MessageBoardIssueDetail.tsx')

test('news article detail page and route are wired to static Markdown documents', () => {
  assert.equal(existsSync(articleDetailPath), true, 'NewsArticleDetail page should exist.')
  assert.equal(existsSync(markdownArticlePath), true, 'MarkdownArticle renderer should exist.')
  assert.equal(existsSync(markdownRendererPath), true, 'Shared markdown renderer should exist.')
  assert.equal(existsSync(newsAnchorPath), true, 'Shared anchor scroll helper should exist.')
  assert.equal(existsSync(articleTocPath), true, 'ArticleToc component should exist.')

  const pageSource = readFileSync(articleDetailPath, 'utf8')
  const newsDocumentsSource = readFileSync(newsDocumentsPath, 'utf8')
  const routerSource = readFileSync(routerPath, 'utf8')
  const markdownSource = readFileSync(markdownArticlePath, 'utf8')
  const rendererSource = readFileSync(markdownRendererPath, 'utf8')
  const newsAnchorSource = readFileSync(newsAnchorPath, 'utf8')
  const tocSource = readFileSync(articleTocPath, 'utf8')
  const indexCssSource = readFileSync(indexCssPath, 'utf8')
  const messageBoardSource = readFileSync(messageBoardPath, 'utf8')
  const messageBoardDetailSource = readFileSync(messageBoardDetailPath, 'utf8')

  assert.match(pageSource, /useParams\(\)/)
  assert.match(pageSource, /getNewsDocumentBySlug\([^)]*\)\.then/)
  assert.match(pageSource, /getAdjacentNewsDocuments\(/)
  assert.match(pageSource, /<MarkdownArticle\s+document=\{document\}\s*\/>/)
  assert.match(pageSource, /<ArticleToc\s+headings=\{document\.headings\}\s*\/>/)
  assert.match(pageSource, /to="\/home\/news"/)
  assert.match(pageSource, /logoSource/)
  assert.match(pageSource, /<header[\s\S]*?<img[\s\S]*?src=\{logoSource\}/)
  assert.match(pageSource, /min-h-screen/)
  assert.match(pageSource, /pt-14/)
  assert.match(pageSource, /fixed inset-x-0 top-0 z-40/)
  assert.match(pageSource, /window\.location\.hash/)
  assert.match(pageSource, /IntersectionObserver/)
  assert.match(pageSource, /replaceState/)
  assert.match(pageSource, /decodeURIComponent\(window\.location\.hash\.slice\(1\)\)/)
  assert.match(pageSource, /observer\.disconnect\(\)/)
  assert.match(pageSource, /isMobileTocOpen/)
  assert.match(pageSource, /setIsMobileTocOpen/)
  assert.match(pageSource, /aria-label="Open article contents"/)
  assert.match(pageSource, /aria-label="Close article contents"/)
  assert.match(pageSource, /fixed inset-0 z-50 lg:hidden/)
  assert.match(pageSource, /hidden lg:sticky/)
  assert.match(pageSource, /keydown/)
  assert.match(pageSource, /Escape/)

  assert.match(routerSource, /NewsArticleDetail/)
  assert.match(routerSource, /path:\s*'news\/:slug'[\s\S]*?<NewsArticleDetail\s*\/>/)
  assert.doesNotMatch(
    routerSource,
    /path:\s*'home'[\s\S]*?children:\s*\[[\s\S]*?path:\s*'news\/:slug'/,
    'news/:slug should be a standalone root route, not a child of /home.',
  )

  assert.match(newsDocumentsSource, /import\.meta\.glob\('\.\.\/\.\.\/content\/news\/\*\.md'/)
  assert.doesNotMatch(newsDocumentsSource, /eager:\s*true/)
  assert.match(newsDocumentsSource, /async function getAllNewsDocuments/)
  assert.match(newsDocumentsSource, /async function getNewsDocumentBySlug/)

  assert.doesNotMatch(markdownSource, /normalizeHeadingText/)
  assert.doesNotMatch(markdownSource, /getTextFromNode/)
  assert.doesNotMatch(markdownSource, /takeNextHeadingId/)
  assert.match(markdownSource, /headingIds=\{document\.headings\.map/)
  assert.match(markdownSource, /id=\{heading\?\.id\}/)
  assert.match(markdownSource, /href=\{`#\$\{heading\?\.id\}`\}/)
  assert.match(markdownSource, /aria-label="Copy heading link"/)
  assert.match(markdownSource, /vp-doc-like min-w-0/)
  assert.match(markdownSource, /MarkdownRenderer/)
  assert.doesNotMatch(markdownSource, /highlightCode/)
  assert.doesNotMatch(markdownSource, /getCodeTokenClass/)

  assert.match(rendererSource, /MarkdownHooks/)
  assert.match(rendererSource, /headingIds/)
  assert.match(rendererSource, /applyHeadingIds/)
  assert.match(rendererSource, /node\.properties\s*=\s*\{[\s\S]*id,/)
  assert.match(rendererSource, /rehypePrettyCode/)
  assert.match(rendererSource, /shiki/)
  assert.match(rendererSource, /github-light/)
  assert.match(rendererSource, /remarkGfm/)
  assert.match(rendererSource, /code: \(/)
  assert.match(rendererSource, /max-w-full/)
  assert.match(rendererSource, /Copy code/)
  assert.match(rendererSource, /navigator\.clipboard\.writeText/)
  assert.match(rendererSource, /group-hover:opacity-100/)
  assert.match(rendererSource, /getTextContent/)
  assert.match(rendererSource, /inline-code/)
  assert.match(rendererSource, /data-line/)
  assert.match(rendererSource, /data-highlighted-line/)

  assert.match(newsAnchorSource, /scrollToHeadingById/)
  assert.match(newsAnchorSource, /requestAnimationFrame/)
  assert.match(newsAnchorSource, /retryCount/)
  assert.match(newsAnchorSource, /behavior:\s*'smooth'/)
  assert.match(indexCssSource, /scroll-behavior:\s*smooth/)
  assert.match(indexCssSource, /article-toc-scrollbar/)

  assert.match(messageBoardSource, /MarkdownRenderer/)
  assert.match(messageBoardSource, /navigate\(`\/board\/\$\{issue\.number\}`\)/)
  assert.match(messageBoardSource, /line-clamp-3/)
  assert.doesNotMatch(messageBoardSource, /max-h-36/)
  assert.doesNotMatch(
    messageBoardSource,
    /<div\s+className="mt-3 line-clamp-3[\s\S]*?onClick=\{\(event\) => event\.stopPropagation\(\)\}[\s\S]*?<MarkdownRenderer/,
    'message board excerpt clicks should bubble to the card detail navigation.',
  )
  assert.doesNotMatch(messageBoardSource, /remarkGfm/)
  assert.doesNotMatch(messageBoardSource, /code: \(\{ children \}\) => \(/)
  assert.match(messageBoardDetailSource, /MarkdownRenderer/)
  assert.match(messageBoardDetailSource, /logoSource/)
  assert.match(messageBoardDetailSource, /min-h-screen bg-\[#f6f6f7\] pt-14 text-\[#213547\]/)
  assert.match(messageBoardDetailSource, /fixed inset-x-0 top-0 z-40/)
  assert.match(messageBoardDetailSource, /to="\/home\/board"/)
  assert.match(messageBoardDetailSource, /to="\/home\/news"/)
  assert.match(messageBoardDetailSource, /bg-\[#ffffff\]/)
  assert.match(messageBoardDetailSource, /border-\[#e2e2e3\]/)
  assert.doesNotMatch(messageBoardDetailSource, /remarkGfm/)
  assert.doesNotMatch(messageBoardDetailSource, /code: \(\{ children \}\) => \(/)

  assert.match(routerSource, /MessageBoardIssueDetail/)
  assert.match(routerSource, /path:\s*'board\/:issueNumber'[\s\S]*?<MessageBoardIssueDetail\s*\/>/)
  assert.doesNotMatch(
    routerSource,
    /path:\s*'home'[\s\S]*?children:\s*\[[\s\S]*?path:\s*'board\/:issueNumber'/,
    'board/:issueNumber should be a standalone root route, not a child of /home.',
  )

  assert.match(pageSource, /scrollToHeadingById\(decodeURIComponent\(hash\.slice\(1\)\)/)
  assert.match(pageSource, /document\.headings\.map\(\(heading\)\s*=>\s*heading\.id\)/)

  assert.match(tocSource, /headings\.map/)
  assert.match(tocSource, /href=\{`#\$\{heading\.id\}`\}/)
  assert.match(tocSource, /onNavigate/)
  assert.match(tocSource, /onClick=\{onNavigate\}/)
  assert.match(tocSource, /max-h-\[calc\(100vh-5rem\)\]/)
  assert.match(tocSource, /overflow-y-auto/)
  assert.match(tocSource, /article-toc-scrollbar/)
  assert.match(tocSource, /truncate/)
  assert.match(tocSource, /whitespace-nowrap/)
  assert.match(tocSource, /min-h-9/)
  assert.match(tocSource, /items-center/)
  assert.match(tocSource, /min-w-0/)
  assert.match(tocSource, /leading-6/)
  assert.match(tocSource, /<span/)
  assert.match(tocSource, /title=\{heading\.text\}/)
  assert.match(tocSource, /bg-\[#ffffff\]/)
  assert.match(tocSource, /text-\[#3c3c43\]/)
  assert.match(tocSource, /border-\[#e2e2e3\]/)
  assert.match(pageSource, /bg-\[#f6f6f7\]/)
  assert.match(pageSource, /bg-\[#ffffff\]/)
})
